### ISSUE TITLE
Create a main CMakeLists.txt 

### ISSUE THREAD

**Issue by miquelmassot** [MecatronicaUSB/mosaic#7]
Currently, the project requires to use VSCode to build everything using g++ commands. Change that to use a multiplatform tool such as CMake to ease its use.

**Comment by vgarciac** [comment]
Hello miquelmassot https://github.com/MecatronicaUSB/mosaic/issues/7#issue-450798020,
The main project consist in the **core** module, which can be build with Cmake.
Here: [core](https://github.com/MecatronicaUSB/mosaic/tree/master/core) you can find the Readme file that explains how to compile and use the mosaic generation system. 

This is already done for each module. The project has this structure since each module works only for a specific and different purpose. It is designed in this way to compile only what you want to use since there are no dependencies between them.

[fcomp](https://github.com/MecatronicaUSB/mosaic/tree/master/fcomp) is a module to make a quick comparison between the different feature detectors and extractors. And [stitch](https://github.com/MecatronicaUSB/mosaic/tree/master/stitch) is a basic module to create a small mosaic.

(these two modules will be removed soon as they are integrated in the main module)

Do not hesitate to ask anything else. I wait for your answer to mark the issue as resolved.
Victor GARCIA

**Comment by miquelmassot** [comment]
Hi @vgarciac,

now I understand, and @cappelletto also explained how it works. I guess there is a lack of documentation. Having a working example would make it easier. I can provide one and PR.
